// ─────────────────────────────────────────────────────────────────────────────
// Project Intelligence Index (Phase 6)
//
// `computeIntelligenceIndex` is a fully DETERMINISTIC scoring model over the
// project's data (no AI involved) — same input always gives the same score.
// `generateIndexFeedback` layers a single AI call on top to turn the index
// into a Danish summary + prioritized actions, with a deterministic fallback
// built from the drivers if the AI call fails or returns malformed JSON.
// ─────────────────────────────────────────────────────────────────────────────

import { Project, Task, PurchaseItem, TimeEntry, ProjectBudgetSummary } from '../../../types';
import { aiChat } from './aiOrchestration';

// ── Types ────────────────────────────────────────────────────────────────────

export type IntelligenceGrade = 'A' | 'B' | 'C' | 'D' | 'E' | 'F';

export type DimensionId = 'planning' | 'budget' | 'schedule' | 'quality' | 'staffing';

export interface IntelligenceDimension {
  id: DimensionId;
  label: string;
  /** 0–100 */
  score: number;
  /** Weight in overall score (sums to 100 across dimensions). */
  weight: number;
  /** Concrete Danish explanations of what raised/lowered the score. */
  drivers: string[];
}

export interface IntelligenceIndex {
  /** 0–100 weighted mean. */
  overall: number;
  grade: IntelligenceGrade;
  dimensions: IntelligenceDimension[];
}

export interface IndexAction {
  title: string;
  why: string;
  impact: 'høj' | 'mellem' | 'lav';
}

export interface IndexFeedback {
  summary: string;
  topActions: IndexAction[];
  risks: string[];
  /** 'ai' when generated by the model, 'fallback' when built from drivers. */
  source: 'ai' | 'fallback';
}

export interface IntelligenceInput {
  project: Project;
  tasks: Task[];
  purchases: PurchaseItem[];
  timeEntries?: TimeEntry[];
  /** When available, the budget dimension uses this (baseline+revisions vs.
   *  purchases+labor+subcontractors) instead of the legacy project.budget/purchases-only calc. */
  budgetSummary?: ProjectBudgetSummary | null;
}

export interface IndexFeedbackContext {
  project: Project;
  tasks: Task[];
  purchases: PurchaseItem[];
}

// ── Helpers ──────────────────────────────────────────────────────────────────

const clamp = (n: number, min = 0, max = 100): number => Math.min(max, Math.max(min, n));

const round = (n: number): number => Math.round(clamp(n));

/** Share (0–1) of items matching a predicate; 0 when the list is empty. */
const share = <T>(items: T[], predicate: (item: T) => boolean): number =>
  items.length === 0 ? 0 : items.filter(predicate).length / items.length;

const parseDate = (value?: string | null): Date | null => {
  if (!value) return null;
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? null : d;
};

const isDone = (task: Task): boolean => task.status === 'Udført';

const purchaseSum = (purchases: PurchaseItem[]): number =>
  purchases.reduce((sum, p) => sum + (p.quantity || 0) * (p.price || 0), 0);

export interface BudgetUtilization {
  totalKr: number;
  committedKr: number;
  /** committedKr / totalKr, 0 when there's no budget to divide by. */
  ratio: number;
}

/**
 * Canonical budget-vs-actual figure, shared by the Intelligence Index's budget
 * dimension and ProjectDetailsTabContent's Performance Index (previously two
 * independent, slightly-diverging re-implementations of the same idea).
 * Prefers the full project_budget_summary (baseline+revisions vs. purchases+
 * labor+subcontractors) when available; falls back to the legacy
 * project.budget.total vs. raw purchases sum otherwise.
 */
export const computeBudgetUtilization = (
  project: Project,
  purchases: PurchaseItem[],
  budgetSummary?: ProjectBudgetSummary | null
): BudgetUtilization => {
  const totalKr = budgetSummary?.hasBaseline ? budgetSummary.plannedTotalKr : (project.budget?.total ?? 0);
  const committedKr = budgetSummary?.hasBaseline ? budgetSummary.actualTotalKr : purchaseSum(purchases);
  return { totalKr, committedKr, ratio: totalKr > 0 ? committedKr / totalKr : 0 };
};

export const gradeFromScore = (score: number): IntelligenceGrade => {
  if (score >= 90) return 'A';
  if (score >= 80) return 'B';
  if (score >= 70) return 'C';
  if (score >= 60) return 'D';
  if (score >= 50) return 'E';
  return 'F';
};

// ── Dimension scoring ────────────────────────────────────────────────────────

const scorePlanning = (input: IntelligenceInput): IntelligenceDimension => {
  const { project, tasks } = input;
  const drivers: string[] = [];
  const n = tasks.length;

  // Task coverage (30%): a real plan has a body of tasks.
  const coverage = clamp((n / 5) * 100);
  if (n === 0) drivers.push('Ingen opgaver er oprettet endnu — planen er tom.');
  else if (n < 5) drivers.push(`Kun ${n} opgave${n === 1 ? '' : 'r'} oprettet — planen virker tynd.`);
  else drivers.push(`${n} opgaver oprettet giver et solidt plangrundlag.`);

  // Descriptions (25%): tasks should be actionable.
  const descShare = share(tasks, t => (t.description?.trim().length ?? 0) >= 10);
  if (n > 0) {
    const withDesc = tasks.filter(t => (t.description?.trim().length ?? 0) >= 10).length;
    if (descShare >= 0.7) drivers.push(`${withDesc} af ${n} opgaver har en beskrivelse.`);
    else drivers.push(`Kun ${withDesc} af ${n} opgaver har en brugbar beskrivelse.`);
  }

  // Dates (25%): task due dates + project start/end.
  const dateShare = share(tasks, t => parseDate(t.dueDate) !== null);
  const hasProjectDates = parseDate(project.startDate) !== null && parseDate(project.endDate) !== null;
  const datesScore = dateShare * 80 + (hasProjectDates ? 20 : 0);
  if (n > 0 && dateShare < 0.8) {
    drivers.push(`${tasks.filter(t => parseDate(t.dueDate) === null).length} opgaver mangler deadline.`);
  }
  if (!hasProjectDates) drivers.push('Projektets start- eller slutdato mangler.');

  // Sequence sanity (20%): dependencies/steps defined and chronologically sane.
  const withSeq = tasks.filter(t => (t.dependencies?.length ?? 0) > 0 || !!t.step).length;
  let seqScore: number;
  if (n === 0) {
    seqScore = 0;
  } else if (withSeq === 0) {
    seqScore = 25;
    drivers.push('Ingen afhængigheder eller rækkefølge mellem opgaver er defineret.');
  } else {
    const byId = new Map(tasks.map(t => [t.id, t]));
    let links = 0;
    let violations = 0;
    tasks.forEach(t => {
      const due = parseDate(t.dueDate);
      (t.dependencies ?? []).forEach(depId => {
        const dep = byId.get(depId);
        if (!dep) return;
        links += 1;
        const depDue = parseDate(dep.dueDate);
        if (due && depDue && due.getTime() < depDue.getTime()) violations += 1;
      });
    });
    const sanity = links === 0 ? 1 : 1 - violations / links;
    seqScore = (withSeq / n) * 60 + sanity * 40;
    if (violations > 0) {
      drivers.push(`${violations} afhængighed${violations === 1 ? '' : 'er'} har deadline før sin forudsætning.`);
    } else {
      drivers.push(`${withSeq} opgaver har rækkefølge/afhængigheder — sekvensen ser fornuftig ud.`);
    }
  }

  const score = round(coverage * 0.3 + descShare * 100 * 0.25 + datesScore * 0.25 + seqScore * 0.2);
  return { id: 'planning', label: 'Planlægning', score, weight: 25, drivers };
};

const scoreBudget = (input: IntelligenceInput): IntelligenceDimension => {
  const { project, purchases, budgetSummary } = input;
  const drivers: string[] = [];

  const { totalKr: total, ratio } = computeBudgetUtilization(project, purchases, budgetSummary);

  // Price data completeness (25%).
  const completeShare = share(purchases, p => (p.price ?? 0) > 0 && (p.quantity ?? 0) > 0);
  if (purchases.length === 0) {
    drivers.push('Ingen indkøb registreret endnu.');
  } else if (completeShare < 0.8) {
    const missing = purchases.filter(p => !((p.price ?? 0) > 0 && (p.quantity ?? 0) > 0)).length;
    drivers.push(`${missing} indkøbslinje${missing === 1 ? '' : 'r'} mangler pris eller antal.`);
  } else {
    drivers.push(`Prisdata er udfyldt på ${purchases.filter(p => (p.price ?? 0) > 0 && (p.quantity ?? 0) > 0).length} af ${purchases.length} indkøbslinjer.`);
  }
  const completenessScore = purchases.length === 0 ? 12 : completeShare * 25;

  if (total <= 0) {
    drivers.unshift('Ingen budgetramme er angivet for projektet.');
    return { id: 'budget', label: 'Budget', score: round(completenessScore), weight: 20, drivers };
  }

  // Budget present (35%).
  drivers.unshift(`Budgetramme på ${total.toLocaleString('da-DK')} kr. er angivet.`);
  if (budgetSummary?.hasBaseline && budgetSummary.actualLaborKr > 0) {
    drivers.push(`Heraf ${Math.round(budgetSummary.actualLaborKr).toLocaleString('da-DK')} kr. i registreret arbejdsomkostning.`);
  }

  // Spend vs budget ratio (40%) — purchases-only when no budget baseline
  // exists, otherwise purchases + labor + subcontractor settlements.
  let ratioScore: number;
  if (ratio <= 0.75) ratioScore = 40;
  else if (ratio <= 0.9) ratioScore = 34;
  else if (ratio <= 1.0) ratioScore = 25;
  else if (ratio <= 1.1) ratioScore = 12;
  else ratioScore = 0;
  const pctUsed = Math.round(ratio * 100);
  if (ratio > 1) drivers.push(`Forbrug overstiger budgettet (${pctUsed} % brugt).`);
  else if (ratio > 0.9) drivers.push(`Budgettet er næsten brugt (${pctUsed} %).`);
  else drivers.push(`Forbrug udgør ${pctUsed} % af budgettet.`);

  // Burn rate vs progress: spending far ahead of progress is a warning sign.
  const progress = clamp(project.progress ?? 0) / 100;
  if (ratio > progress + 0.2 && ratio > 0.3) {
    ratioScore = Math.max(0, ratioScore - 8);
    drivers.push(`Forbruget (${pctUsed} %) ligger foran fremdriften (${Math.round(progress * 100)} %).`);
  }

  const score = round(35 + ratioScore + completenessScore);
  return { id: 'budget', label: 'Budget', score, weight: 20, drivers };
};

const scoreSchedule = (input: IntelligenceInput): IntelligenceDimension => {
  const { project, tasks } = input;
  const drivers: string[] = [];
  const now = Date.now();

  const start = parseDate(project.startDate);
  const end = parseDate(project.endDate);
  const open = tasks.filter(t => !isDone(t));
  const doneRatio = tasks.length > 0 ? tasks.filter(isDone).length / tasks.length : clamp(project.progress ?? 0) / 100;

  // Pace vs deadline (50%).
  let paceScore: number;
  if (!end) {
    paceScore = 20;
    drivers.push('Projektet mangler en slutdato — tidsplanen kan ikke vurderes præcist.');
  } else if (end.getTime() < now && doneRatio < 1) {
    paceScore = 0;
    drivers.push(`Slutdatoen ${end.toLocaleDateString('da-DK')} er overskredet med ufærdige opgaver.`);
  } else {
    const startMs = start?.getTime() ?? end.getTime() - 90 * 86400000;
    const span = Math.max(1, end.getTime() - startMs);
    const elapsedRatio = clamp(((now - startMs) / span) * 100) / 100;
    const diff = doneRatio - elapsedRatio;
    if (diff >= 0) paceScore = 50;
    else if (diff >= -0.15) paceScore = 35;
    else if (diff >= -0.3) paceScore = 20;
    else paceScore = 5;
    const donePct = Math.round(doneRatio * 100);
    const elapsedPct = Math.round(elapsedRatio * 100);
    if (diff >= 0) drivers.push(`Fremdriften (${donePct} %) følger eller overgår den forløbne tid (${elapsedPct} %).`);
    else drivers.push(`Fremdriften (${donePct} %) halter efter den forløbne tid (${elapsedPct} %).`);
  }

  // Overdue tasks (50%).
  const overdue = open.filter(t => {
    if (t.status === 'Forfalden') return true;
    const due = parseDate(t.dueDate);
    return due !== null && due.getTime() < now;
  });
  const overdueShare = tasks.length > 0 ? overdue.length / tasks.length : 0;
  const overdueScore = tasks.length === 0 ? 25 : 50 * (1 - Math.min(1, overdueShare * 2));
  if (overdue.length > 0) {
    drivers.push(`${overdue.length} opgave${overdue.length === 1 ? ' er' : 'r er'} forfalden${overdue.length === 1 ? '' : 'e'}.`);
  } else if (tasks.length > 0) {
    drivers.push('Ingen forfaldne opgaver.');
  } else {
    drivers.push('Ingen opgaver at vurdere tidsplanen ud fra.');
  }

  const score = round(paceScore + overdueScore);
  return { id: 'schedule', label: 'Tidsplan', score, weight: 25, drivers };
};

const scoreQuality = (input: IntelligenceInput): IntelligenceDimension => {
  const { project, tasks } = input;
  const drivers: string[] = [];
  const n = tasks.length;

  // Documentation on tasks: attachments/photos (30%), checklists (30%), comments (20%).
  const attachShare = share(tasks, t => (t.attachments?.length ?? 0) > 0);
  const checklistShare = share(tasks, t => (t.checklist?.length ?? 0) > 0);
  const commentShare = share(tasks, t => (t.comments?.length ?? 0) > 0);

  if (n > 0) {
    const withAttach = tasks.filter(t => (t.attachments?.length ?? 0) > 0).length;
    if (attachShare >= 0.4) drivers.push(`${withAttach} af ${n} opgaver har fotos eller dokumenter vedhæftet.`);
    else drivers.push(`Kun ${withAttach} af ${n} opgaver har fotos/dokumentation vedhæftet.`);

    const withChecklist = tasks.filter(t => (t.checklist?.length ?? 0) > 0).length;
    if (checklistShare >= 0.4) drivers.push(`${withChecklist} af ${n} opgaver har en kvalitetstjekliste.`);
    else drivers.push(`Kun ${withChecklist} af ${n} opgaver har en tjekliste tilknyttet.`);
  } else {
    drivers.push('Ingen opgaver — ingen opgavedokumentation at vurdere.');
  }

  // Project-level docs (20%): description + floor plan.
  const hasDesc = (project.description?.trim().length ?? 0) >= 30;
  const hasPlan = !!project.floorPlanUrl;
  if (!hasDesc) drivers.push('Projektbeskrivelsen er kort eller mangler.');
  if (hasPlan) drivers.push('Plantegning er uploadet til projektet.');
  const projectDocsScore = (hasDesc ? 10 : 0) + (hasPlan ? 10 : 0);

  const score = round(attachShare * 30 + checklistShare * 30 + commentShare * 20 + projectDocsScore);
  return { id: 'quality', label: 'Kvalitet & dokumentation', score, weight: 15, drivers };
};

const scoreStaffing = (input: IntelligenceInput): IntelligenceDimension => {
  const { project, tasks, timeEntries } = input;
  const drivers: string[] = [];
  const n = tasks.length;

  // Assignee coverage (50%).
  const assignedShare = share(tasks, t => (t.assignees?.length ?? 0) > 0);
  if (n > 0) {
    const withAssignee = tasks.filter(t => (t.assignees?.length ?? 0) > 0).length;
    if (assignedShare >= 0.8) drivers.push(`${withAssignee} af ${n} opgaver har en ansvarlig.`);
    else drivers.push(`${n - withAssignee} opgave${n - withAssignee === 1 ? '' : 'r'} mangler en ansvarlig.`);
  } else {
    drivers.push('Ingen opgaver at bemande endnu.');
  }

  // Workload spread (30%): is the open work concentrated on one person?
  const open = tasks.filter(t => !isDone(t));
  const loadByAssignee = new Map<string, number>();
  let openAssigned = 0;
  open.forEach(t => {
    (t.assignees ?? []).forEach(a => {
      loadByAssignee.set(a.id, (loadByAssignee.get(a.id) ?? 0) + 1);
      openAssigned += 1;
    });
  });
  let spreadScore: number;
  if (openAssigned === 0) {
    spreadScore = n === 0 ? 0 : 8;
  } else if (loadByAssignee.size === 1 && openAssigned > 2) {
    spreadScore = 8;
    drivers.push('Alle åbne opgaver ligger hos én person — sårbar bemanding.');
  } else {
    const maxLoad = Math.max(...loadByAssignee.values());
    const maxShare = maxLoad / openAssigned;
    if (maxShare <= 0.5) spreadScore = 30;
    else if (maxShare <= 0.7) spreadScore = 20;
    else if (maxShare <= 0.85) spreadScore = 12;
    else spreadScore = 6;
    if (maxShare > 0.7) drivers.push(`Én person bærer ${Math.round(maxShare * 100)} % af de åbne opgaver.`);
    else drivers.push('Arbejdsbyrden er rimeligt fordelt på teamet.');
  }

  // Team size (20%).
  const teamSize = project.team?.length ?? 0;
  const teamScore = teamSize >= 2 ? 20 : teamSize === 1 ? 10 : 0;
  if (teamSize === 0) drivers.push('Ingen teammedlemmer er tilknyttet projektet.');
  else if (teamSize === 1) drivers.push('Kun ét teammedlem på projektet.');
  else drivers.push(`${teamSize} teammedlemmer er tilknyttet projektet.`);

  if (timeEntries && timeEntries.length > 0) {
    const hours = timeEntries.reduce((s, e) => s + (e.hours || 0), 0);
    drivers.push(`${hours.toLocaleString('da-DK')} timer er registreret på projektet.`);
  }

  const score = round(assignedShare * 50 + spreadScore + teamScore);
  return { id: 'staffing', label: 'Bemanding', score, weight: 15, drivers };
};

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Deterministic Project Intelligence Index.
 * Five dimensions (0–100 each), weighted 25/20/25/15/15 into an overall
 * score, mapped to grades A (≥90) … F (<50).
 */
export const computeIntelligenceIndex = (input: IntelligenceInput): IntelligenceIndex => {
  const dimensions: IntelligenceDimension[] = [
    scorePlanning(input),
    scoreBudget(input),
    scoreSchedule(input),
    scoreQuality(input),
    scoreStaffing(input),
  ];

  const totalWeight = dimensions.reduce((s, d) => s + d.weight, 0);
  const overall = round(
    dimensions.reduce((s, d) => s + d.score * d.weight, 0) / Math.max(1, totalWeight)
  );

  return { overall, grade: gradeFromScore(overall), dimensions };
};

// ── AI feedback ──────────────────────────────────────────────────────────────

/** Strip markdown fences and extract the outermost JSON object from AI text. */
const extractJson = (text: string): unknown => {
  const cleaned = text.replace(/```(?:json)?/gi, '').trim();
  const start = cleaned.indexOf('{');
  const end = cleaned.lastIndexOf('}');
  if (start === -1 || end === -1 || end <= start) throw new Error('No JSON object in AI response');
  return JSON.parse(cleaned.slice(start, end + 1));
};

const coerceImpact = (value: unknown): IndexAction['impact'] => {
  const v = String(value ?? '').toLowerCase();
  if (v.includes('høj') || v.includes('hoj') || v === 'high') return 'høj';
  if (v.includes('lav') || v === 'low') return 'lav';
  return 'mellem';
};

/** Deterministic feedback built from the index drivers — no AI required. */
export const buildFallbackFeedback = (index: IntelligenceIndex): IndexFeedback => {
  const sorted = [...index.dimensions].sort((a, b) => a.score - b.score);
  const weakest = sorted.slice(0, 2);
  const strongest = sorted[sorted.length - 1];

  const summary =
    `Projektet scorer ${index.overall}/100 (karakter ${index.grade}). ` +
    `Stærkeste område er ${strongest.label.toLowerCase()} (${strongest.score}), ` +
    `mens ${weakest.map(d => d.label.toLowerCase()).join(' og ')} trækker ned ` +
    `(${weakest.map(d => d.score).join(' og ')}).`;

  const actionTitleByDim: Record<DimensionId, string> = {
    planning: 'Styrk planlægningen med beskrivelser, deadlines og rækkefølge',
    budget: 'Få styr på budgetramme og prisdata på indkøb',
    schedule: 'Håndtér forfaldne opgaver og genberegn tidsplanen',
    quality: 'Tilføj fotos, tjeklister og dokumentation på opgaverne',
    staffing: 'Fordel ansvar og arbejdsbyrde på flere teammedlemmer',
  };

  const topActions: IndexAction[] = weakest.map((dim, i) => ({
    title: actionTitleByDim[dim.id],
    why: dim.drivers[0] ?? `${dim.label} scorer kun ${dim.score}/100.`,
    impact: i === 0 ? 'høj' : 'mellem',
  }));

  const risks = index.dimensions
    .filter(d => d.score < 50)
    .map(d => `${d.label} er kritisk lav (${d.score}/100): ${d.drivers[0] ?? 'kræver handling'}`);

  return { summary, topActions, risks, source: 'fallback' };
};

/**
 * One AI call that turns the deterministic index into Danish feedback.
 * Falls back to `buildFallbackFeedback` on any error or malformed JSON.
 */
export const generateIndexFeedback = async (
  index: IntelligenceIndex,
  context: IndexFeedbackContext
): Promise<IndexFeedback> => {
  const { project, tasks, purchases } = context;
  const openTasks = tasks.filter(t => t.status !== 'Udført').length;

  const prompt = `Projekt: "${project.name}" (status: ${project.status}, fremdrift: ${project.progress}%).
Kunde: ${project.clientName || 'ukendt'}. Periode: ${project.startDate || '?'} – ${project.endDate || '?'}.
Opgaver: ${tasks.length} i alt, ${openTasks} åbne. Indkøbslinjer: ${purchases.length}.

Intelligensindeks (deterministisk beregnet):
Samlet: ${index.overall}/100 (karakter ${index.grade})
${index.dimensions
  .map(d => `- ${d.label}: ${d.score}/100 (vægt ${d.weight}%)\n  Drivere: ${d.drivers.join(' | ')}`)
  .join('\n')}

Returnér KUN gyldig JSON (ingen markdown, ingen forklaring) på dansk i dette format:
{"summary": "2-3 sætninger om projektets tilstand", "topActions": [{"title": "konkret handling", "why": "kort begrundelse", "impact": "høj|mellem|lav"}], "risks": ["konkret risiko", "..."]}
Maks 4 topActions og maks 4 risks. Vær konkret og handlingsorienteret som en erfaren dansk byggeleder.`;

  try {
    const text = await aiChat({
      prompt,
      system:
        'Du er en erfaren dansk byggeleder og projektchef. Du svarer altid udelukkende med gyldig JSON uden markdown-formatering.',
      feature: 'project-evaluation',
      temperature: 0.4,
    });

    const raw = extractJson(text) as {
      summary?: unknown;
      topActions?: unknown;
      risks?: unknown;
    };

    const summary = typeof raw.summary === 'string' && raw.summary.trim() ? raw.summary.trim() : null;
    const topActions: IndexAction[] = Array.isArray(raw.topActions)
      ? raw.topActions
          .filter((a): a is Record<string, unknown> => !!a && typeof a === 'object')
          .map(a => ({
            title: String(a.title ?? '').trim(),
            why: String(a.why ?? '').trim(),
            impact: coerceImpact(a.impact),
          }))
          .filter(a => a.title)
          .slice(0, 4)
      : [];
    const risks: string[] = Array.isArray(raw.risks)
      ? raw.risks.map(r => String(r ?? '').trim()).filter(Boolean).slice(0, 4)
      : [];

    if (!summary || topActions.length === 0) {
      // AI returned something unusable — degrade gracefully.
      return buildFallbackFeedback(index);
    }

    return { summary, topActions, risks, source: 'ai' };
  } catch {
    return buildFallbackFeedback(index);
  }
};
